config/routes.rb
Hds::Application.routes.draw do
  
  get 'books/search_authors'
  get 'books/search_illustrators'
  get 'books/search_publishers'
  get 'books/search_themes'
  post 'books/search_tags'
  post 'books/search_for'
  put 'reviews/select_shelf'
  put 'reviews/change_shelf'
  get 'profiles/search_followable_users'
  get 'shelves/list'
  get 'shelves/gridlist'
  match 'publishers/collections_by_publisher/:name' => "publishers#collections_by_publisher", :via => :get

  devise_for :users  
  resources :users do
    resources :profile, :controller => :profiles, :name_prefix => "user_"
  end
  resources :profiles, :only => [:show, :edit] do
    resources :shelves, :name_prefix => "profile_"
    resources :children, :name_prefix => "profile_"
  end
  resources :shelves do
    resources :books, :name_prefix => "shelf_"
  end
  resources :publishers do
    resources :collections
  end
  resources :authors
  resources :illustrators
  resources :collections
  resources :categories do
    get "list_books"
  end
  resources :book_types
  resources :themes do 
    get "list_books"
  end
  resources :books do 
    resources :reviews, :name_prefix => "book_"
  end
  resources :children, :only => [:show]
  resources :reviews
  resources :follows
  resources :tags
    
  
  

  root :to => 'home#index'

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  validates_length_of :name, :in => 2..255
  validates_uniqueness_of :name
  belongs_to :publisher
  has_many :books
  attr_accessible :name, :publisher_id
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.all
    @new_collection = Collection.new
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @collections }
    end
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
    @collection = Collection.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @collection }
    end
  end

  # GET /collections/new
  # GET /collections/new.json
  def new
    @collection = Collection.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @collection }
    end
  end

  # GET /collections/1/edit
  def edit
    @collection = Collection.find(params[:id])
  end

  # POST /collections
  # POST /collections.json
  def create
    @publisher = Publisher.find(params[:publisher_id])
    @collection = @publisher.collections.create(params[:collection])
    redirect_to publisher_path(@publisher)
#    @collection = Collection.new(params[:collection])

#    respond_to do |format|
#      if @collection.save
#        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
#        format.json { render json: @collection, status: :created, location: @collection }
#      else
#        format.html { render action: "new" }
#        format.json { render json: @collection.errors, status: :unprocessable_entity }
#      end
#    end
  end

  # PUT /collections/1
  # PUT /collections/1.json
  def update
    @collection = Collection.find(params[:id])

    respond_to do |format|
      if @collection.update_attributes(params[:collection])
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection = Collection.find(params[:id])
    @collection.destroy

    respond_to do |format|
      format.html { redirect_to collections_url }
      format.json { head :no_content }
    end
  end
end

app/views/collections/_form.html.haml
= form_for(@collection) do |f|
  %dl.dl-horizontal
    .field
      %dt= f.label :name
      %dd= f.text_field :name
    .field
      %dt= f.label :publisher
      %dd
        = f.collection_select(:publisher_id, Publisher.all, :id, :name)
  .actions
    = f.submit

app/views/collections/edit.html.haml
%h1 Editing collection

= render 'form'

= link_to 'Show', @collection
\|
= link_to 'Back', collections_path

app/views/collections/index.html.haml
%script{:type => "text/javascript"}
  :plain 

    $(document).ready(function() {
      /* Activating Best In Place */
      jQuery(".best_in_place").best_in_place(); 
    });

- content_for(:subnav) do
  = render 'layouts/config_subnavigation'
  
%h1 Collections
#new_collection.pull-right
  = form_for @new_collection, :html => {:class => "form-inline", :id => "new_collection_form"} do |f|
    %strong New:
    = f.text_field :name, :placeholder => "Collection Name"
    = select_tag(:publisher_id, options_for_select(Publisher.all.collect {|p| [p.name, p.id]}))
    = f.submit 
%small NB: Double-click on a field to edit it
%br
%br
%table.table.table-hover.table-striped.table-condensed
  %thead
    %tr
      %th Name
      %th Publisher
      %th Actions
  %tbody
  - @collections.each do |collection|
    %tr
      %td= best_in_place collection, :name, :type => :input
      %td= best_in_place collection, :publisher_id, :type => :select, :collection => Publisher.all.collect {|p| [p.id, p.name]}
      %td
        = link_to 'Details', collection, :class => 'btn btn-mini'
        = link_to 'Destroy', collection, :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-danger btn-mini'

app/views/collections/new.html.haml
%h1 New collection

= render 'form'

= link_to 'Back', collections_path

app/views/collections/show.html.haml
%br
%h1= @collection.name
%br
.page-header
  %strong
    = "Published by "
    = link_to @collection.publisher.name, publisher_path(@collection.publisher)
- if @collection.books.size == 0
  %p= "No books found for "+@collection.name+"."
- else 
  %ul.thumbnails{:id => "grid"}
    - @collection.books.each do |book|
      %li
        .thumbnail
          %a{:href => book_path(book)}
            = image_tag(book.cover.url(:tiny))