config/routes.rb
Hds::Application.routes.draw do
  
  get 'books/search_authors'
  get 'books/search_illustrators'
  get 'books/search_publishers'
  get 'books/search_themes'
  post 'books/search_tags'
  post 'books/search_for'
  put 'reviews/select_shelf'
  put 'reviews/change_shelf'
  get 'profiles/search_followable_users'
  get 'shelves/list'
  get 'shelves/gridlist'
  match 'publishers/collections_by_publisher/:name' => "publishers#collections_by_publisher", :via => :get

  devise_for :users  
  resources :users do
    resources :profile, :controller => :profiles, :name_prefix => "user_"
  end
  resources :profiles, :only => [:show, :edit] do
    resources :shelves, :name_prefix => "profile_"
    resources :children, :name_prefix => "profile_"
  end
  resources :shelves do
    resources :books, :name_prefix => "shelf_"
  end
  resources :publishers do
    resources :collections
  end
  resources :authors
  resources :illustrators
  resources :collections
  resources :categories do
    get "list_books"
  end
  resources :book_types
  resources :themes do 
    get "list_books"
  end
  resources :books do 
    resources :reviews, :name_prefix => "book_"
  end
  resources :children, :only => [:show]
  resources :reviews
  resources :follows
  resources :tags
    
  
  

  root :to => 'home#index'

end

app/controllers/shelves_controller.rb
class ShelvesController < ApplicationController
  
  respond_to :html, :xml, :json
  # GET /shelves
  # GET /shelves.json
  def index
    @profile = Profile.find(params[:profile_id])
    if @profile.user == current_user
      logger.debug("Current user wanna see his/her shelves")
    else 
      logger.debug("Current user wanna see another user shelves")
    end
    @shelves = @profile.shelves
    @all_shelves_books = Array.new
    if !@shelves.empty?
      @shelves.each do |shelf|
        if !shelf.books.empty?
          shelf.books.each do |book|
            @all_shelves_books << book
          end
        end
      end
    end
    respond_with(@shelves)
  end

  def list
    @shelves = current_user.profile.shelves
    @all_shelves_books = Array.new
    if !@shelves.empty?
      @shelves.each do |shelf|
        if !shelf.books.empty?
          shelf.books.each do |book|
            @all_shelves_books << book
          end
        end
      end
    end
    render :layout => false
  end

  def gridlist
    @shelves = current_user.profile.shelves
    @all_shelves_books = Array.new
    if !@shelves.empty?
      @shelves.each do |shelf|
        if !shelf.books.empty?
          shelf.books.each do |book|
            @all_shelves_books << book
          end
        end
      end
    end
    render :layout => false
  end

  # GET /shelves/1
  # GET /shelves/1.json
  def show
    @shelf = Shelf.find(params[:id])
    render :layout => false
#    respond_to do |format|
#      format.html # show.html.erb
#      format.json { render json: @shelf }
#      format.js
#    end
  end

  # GET /shelves/new
  # GET /shelves/new.json
  def new
    @shelf = Shelf.new
    @profile = Profile.find(params[:profile_id])
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shelf }
    end
  end

  # GET /shelves/1/edit
  def edit
    @shelf = Shelf.find(params[:id])
  end

  # POST /shelves
  # POST /shelves.json
  def create
    @profile = Profile.find(params[:profile_id])
    @shelf = @profile.shelves.create(params[:shelf])
    
    respond_to do |format|
      if @shelf.save
        format.html { redirect_to profile_shelves_path(@profile), notice: 'Shelf was successfully created.' }
        format.json { render json: @shelf, status: :created, location: @shelf }
      else
        format.html { render action: "new" }
        format.json { render json: @shelf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shelves/1
  # PUT /shelves/1.json
  def update
    @shelf = Shelf.find(params[:id])

    respond_to do |format|
      if @shelf.update_attributes(params[:shelf])
        format.html { redirect_to @shelf, notice: 'Shelf was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shelf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shelves/1
  # DELETE /shelves/1.json
  def destroy
    @shelf = Shelf.find(params[:id])
    @profile = @shelf.profile
    @shelf.destroy

    respond_to do |format|
      format.html { redirect_to profile_shelves_path(@profile) }
      format.json { head :no_content }
    end
  end
end

app/helpers/shelves_helper.rb
module ShelvesHelper
end

app/views/shelves/_covers_grid.html.haml
- if @all_shelves_books.size == 0
  %p No books found in the library.
- else 
  %ul.thumbnails{:id => "grid"}
    - @all_shelves_books.each do |book|
      %li
        .thumbnail
          %a{:href => book_path(book)}
            = image_tag(book.cover.url(:tiny))

app/views/shelves/_form.html.haml
= form_for([@profile, @profile.shelves.build]) do |f|
  %dl.dl-horizontal
    .field
      %dt= f.label :name
      %dd= f.text_field :name
    .field
      %dt= f.label :description
      %dd= f.text_field :description
  .actions
    = f.submit

app/views/shelves/edit.html.haml
%h1 Editing shelf

= render 'form'

= link_to 'Show', @shelf
\|
= link_to 'Back', shelves_path

app/views/shelves/gridlist.html.haml
= render 'covers_grid'

app/views/shelves/index.html.haml
%script{:type => "text/javascript"}
  :plain
  
    $(document).ready(function() { 
      $(".nav-list a").displayWithAjax("#shelves_details");
      $("#listview").click(
        function () { 
          $('#gridview').removeClass("active"); 
          hide_load_and_show_div("#shelves_details","/shelves/list");
          $('#listview').addClass("active");
          // Empecher l'action par défaut du bouton submit 
          return false;
      });
      $("#gridview").click(
        function () { 
          $('#listview').removeClass("active"); 
          hide_load_and_show_div("#shelves_details","/shelves/gridlist");
          $('#gridview').addClass("active");
          // Empecher l'action par défaut du bouton submit 
          return false;
      });
    });
%br
%h1 
  My Library
  .btn-group.pull-right
    #gridview.btn.active
      %i.icon-th
    #listview.btn
      %i.icon-th-list
%br
.row
  .span4
    #shelves_list.well{:style => "padding: 8px 0;"}
      %ul.nav.nav-list
        - @shelves.each do |shelf|
          %li
            %a{:href => shelf_path(shelf)}
              %i.icon-book
              = shelf.name
              = "(#{shelf.books.size})"
            - if !['to_read','read','currently_reading'].include?(shelf.name)
              = link_to '', shelf, :confirm => 'Are you sure?', :method => :delete, :class => 'icon-remove pull-right'
  #shelves_details.span8
    = render 'covers_grid'

%br

= link_to 'New Shelf', new_profile_shelf_path

app/views/shelves/list.html.haml
- if @all_shelves_books.size == 0
  %p No books found in the library.
- else 
  - @all_shelves_books.each do |book|
    .media
      %a.pull-left{:href => book_path(book)}
        = image_tag(book.cover.url(:tiny), :class => "media-object")
      .media-body
        %h4.media-heading= book.title
        %small
          - book.authors.each do |a|
            - if a == book.authors.first
              = link_to a.name, a
            - else 
              = ", "
              = link_to a.name, a
        %p= book.publisher_resume

app/views/shelves/new.html.haml
%h1 New shelf

= render 'form'

= link_to 'Back', shelves_path

app/views/shelves/show.html.haml
%p#notice= notice
.page-header
  %h4
    = @shelf.name
    %a.btn.btn-mini.pull-right{:href => edit_profile_shelf_path(@shelf.profile,@shelf)}
      %i.icon-pencil
      Edit Shelf
    %small= @shelf.description
  %h6= "(#{@shelf.books.size} books)"
- if @shelf.books.size != 0
  .thumbnails
  - @shelf.books.each do |book|
    .span1
      %a{:href => book_path(book)}
        = image_tag book.cover.url(:tiny)
  