config/routes.rb
Hds::Application.routes.draw do
  
  get 'books/search_authors'
  get 'books/search_illustrators'
  get 'books/search_publishers'
  get 'books/search_themes'
  post 'books/search_tags'
  post 'books/search_for'
  put 'reviews/select_shelf'
  put 'reviews/change_shelf'
  get 'profiles/search_followable_users'
  get 'shelves/list'
  get 'shelves/gridlist'
  match 'publishers/collections_by_publisher/:name' => "publishers#collections_by_publisher", :via => :get

  devise_for :users  
  resources :users do
    resources :profile, :controller => :profiles, :name_prefix => "user_"
  end
  resources :profiles, :only => [:show, :edit] do
    resources :shelves, :name_prefix => "profile_"
    resources :children, :name_prefix => "profile_"
  end
  resources :shelves do
    resources :books, :name_prefix => "shelf_"
  end
  resources :publishers do
    resources :collections
  end
  resources :authors
  resources :illustrators
  resources :collections
  resources :categories do
    get "list_books"
  end
  resources :book_types
  resources :themes do 
    get "list_books"
  end
  resources :books do 
    resources :reviews, :name_prefix => "book_"
  end
  resources :children, :only => [:show]
  resources :reviews
  resources :follows
  resources :tags
    
  
  

  root :to => 'home#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
  validates_presence_of :first_name, :last_name
  has_and_belongs_to_many :books
  attr_accessible :first_name, :last_name
  def name
    "#{first_name} #{last_name}"
  end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
    @new_author = Author.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authors }
    end
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @author = Author.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/new
  # GET /authors/new.json
  def new
    @author = Author.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(params[:author])
   
    respond_to do |format|
      if @author.save
        format.html { redirect_to '/authors', notice: 'Author was successfully created.' }
        format.json { render json: @author, status: :created, location: @authors }
      else
        format.html { redirect_to '/authors', errors: 'Author could not be created.' }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /authors/1
  # PUT /authors/1.json
  def update
    @author = Author.find(params[:id])

    respond_to do |format|
      if @author.update_attributes(params[:author])
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end
end

app/views/authors/_form.html.haml
= form_for(@author, :class => 'form-horizontal') do |f|
  %dl.dl-horizontal
    .field
      %dt= f.label :last_name
      %dd= f.text_field :last_name
      %dt= f.label :first_name
      %dd= f.text_field :first_name
  .actions
    = f.submit

app/views/authors/edit.html.haml
%h1 Editing author

= render 'form'

= link_to 'Show', @author
\|
= link_to 'Back', authors_path

app/views/authors/index.html.haml
%script{:type => "text/javascript"}
  :plain 

    $(document).ready(function() {
      /* Activating Best In Place */
      jQuery(".best_in_place").best_in_place(); 
    });

- content_for(:subnav) do
  = render 'layouts/config_subnavigation'
  
%h1 Authors
#new_author.pull-right
  = form_for @new_author, :html => {:class => "form-inline", :id => "new_author_form"} do |f|
    %strong New:
    = f.text_field :last_name, :placeholder => "Author Last Name"
    = f.text_field :first_name, :placeholder => "Author First Name" 
    = f.submit
%small NB: Double-click on a name to edit it
%br
%br
%table.table.table-striped.table-hover.table-condensed
  %tr
    %th Last Name
    %th First Name
    %th Actions
  - @authors.each do |author|
    %tr
      %td= best_in_place author, :last_name, :type => :input
      %td= best_in_place author, :first_name, :type => :input
      %td
        = link_to 'Details', author, :class => 'btn btn-mini'
        = link_to 'Destroy', author, :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-danger btn-mini'

%br

app/views/authors/new.html.haml
%h1 New author

= render 'form'

= link_to 'Back', authors_path

app/views/authors/show.html.haml
%br
%h1= @author.name
%br
.page-header
  %strong Bibliography
- if @author.books.size == 0
  %p= "No books found for "+@author.name+"."
- else 
  %ul.thumbnails{:id => "grid"}
    - @author.books.each do |book|
      %li
        .thumbnail
          %a{:href => book_path(book)}
            = image_tag(book.cover.url(:tiny))