config/routes.rb
Hds::Application.routes.draw do
  
  get 'books/search_authors'
  get 'books/search_illustrators'
  get 'books/search_publishers'
  get 'books/search_themes'
  post 'books/search_tags'
  post 'books/search_for'
  put 'reviews/select_shelf'
  put 'reviews/change_shelf'
  get 'profiles/search_followable_users'
  get 'shelves/list'
  get 'shelves/gridlist'
  match 'publishers/collections_by_publisher/:name' => "publishers#collections_by_publisher", :via => :get

  devise_for :users  
  resources :users do
    resources :profile, :controller => :profiles, :name_prefix => "user_"
  end
  resources :profiles, :only => [:show, :edit] do
    resources :shelves, :name_prefix => "profile_"
    resources :children, :name_prefix => "profile_"
  end
  resources :shelves do
    resources :books, :name_prefix => "shelf_"
  end
  resources :publishers do
    resources :collections
  end
  resources :authors
  resources :illustrators
  resources :collections
  resources :categories do
    get "list_books"
  end
  resources :book_types
  resources :themes do 
    get "list_books"
  end
  resources :books do 
    resources :reviews, :name_prefix => "book_"
  end
  resources :children, :only => [:show]
  resources :reviews
  resources :follows
  resources :tags
    
  
  

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @books = Book.all
    @last_entries = Book.order("created_at DESC").limit(10)
    @most_reviewed = Book.all(:select => "books.*, COUNT(book_id) as reviews_count",
            :joins  => "LEFT JOIN reviews AS reviews ON reviews.book_id = books.id",
            :group  => "reviews.book_id",
            :order  => "reviews_count DESC",
            :conditions  => "reviews.details IS NOT NULL",
            :limit => 5)
    @populars = Book.all(:select => "books.*, AVG(rating) as average_rating",
            :joins  => "LEFT JOIN reviews AS reviews ON reviews.book_id = books.id",
            :group  => "reviews.book_id",
            :order  => "average_rating DESC",
            :conditions  => "reviews.rating IS NOT NULL",
            :limit => 5)
    #@coup_coeur = Book.order("created_at DESC").limit(10)

    @tags = Book.tag_counts_on(:tags)
    @last_reviews = Review.all(:conditions => "details IS NOT NULL", :order => "created_at DESC", :limit => 5)

    if user_signed_in?
      if current_user.profile.nil?
        logger.debug(current_user.id)
        @profile = current_user.build_profile()
        if @profile.save
          logger.debug("Profile created")
          redirect_to edit_user_profile_path(current_user,@profile)
        else
          logger.debug("Profile not created")
        end
      end
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/home/index.html.haml
= stylesheet_link_tag params[:controller]
/ = stylesheet_link_tag "label"
= javascript_include_tag "modernizr.custom.js"

%br
- if !user_signed_in?
  .hero-unit
    .row-fluid
      .span6
        %h1 Children books referential
        %br
        %p 
          You don't know what to read to your children ...
          %br
          You want books to help your children confronting their fears ... 
          %br
          You're expecting and you want to explain your children what's going on ...
          %br
      .span3.pull-right
        %h3 New to BokBok ?
        %h4 Create a free account
        = render 'devise/registrations/form'

.row-fluid
  .span8
    .main.clearfix
      %ul.bb-custom-grid.cs-style-6{:id => "bb-custom-grid"}
        %li
          %h3 Last Entries
          .bb-bookblock
            - if @last_entries.size > 0
              - @last_entries.each do |book|
                .bb-item
                  %a{:href => book_path(book)}
                    = image_tag(book.cover.url(:bookblock))
          %nav
            - if @last_entries.size > 1
              - @last_entries.each do |book|
                - if book == @last_entries.first
                  %span.bb-current
                - else 
                  %span
        %li
          %h3 Top 5
          .bb-bookblock
            - if @populars.size > 0
              - @populars.each do |book|
                .bb-item
                  %a{:href => book_path(book)}
                    = image_tag(book.cover.url(:bookblock))
          %nav
            - if @populars.size > 1
              - @populars.each do |book|
                - if book == @populars.first
                  %span.bb-current
                - else 
                  %span
        %li
          %h3 Most Reviewed
          .bb-bookblock
            - if @most_reviewed.size > 0
              - @most_reviewed.each do |book|
                .bb-item
                  %a{:href => book_path(book)}
                    = image_tag(book.cover.url(:bookblock))
          %nav
            - if @most_reviewed.size > 1
              - @most_reviewed.each do |book|
                - if book == @most_reviewed.first
                  %span.bb-current
                - else 
                  %span
        %li
          %h3 Coup de coeur
          .bb-bookblock
            .bb-item
              %a{:href => "http://dribbble.com/shots/702201-Cat"}
                %img{:src => "http://dribbble.s3.amazonaws.com/users/42865/screenshots/702201/cat.jpg"}
            .bb-item
              %a{:href => "http://dribbble.com/shots/493644-Death-Planet"}
                %img{:src => "http://dribbble.s3.amazonaws.com/users/42865/screenshots/493644/deathplanet.png"}
            .bb-item
              %a{:href => "http://dribbble.com/shots/432311-Bearwolf"}
                %img{:src => "http://dribbble.s3.amazonaws.com/users/42865/screenshots/432311/bearwolf.png"}
            .bb-item
              %a{:href => "http://dribbble.com/shots/297337-iPhone-4S"}
                %img{:src => "http://dribbble.s3.amazonaws.com/users/42865/screenshots/297337/ilus2.png"}
          %nav
            %span.bb-current
            %span
            %span
            %span
  .span4
    - if !user_signed_in?
      .well
        %form.navbar-search.pull-left{:action => ''}
          .input-append
            %input{:type => "text", :placeholder => "Title / Author / ISBN"}
              %span.add-on
                %i.icon-search
        %br
    .well
      %h4 Tags
      - tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class|
        = link_to tag.name, tag_path(:id => tag.name), :class => css_class
    .well
      %h4 Last reviews
      - if @last_reviews.size > 0
        - @last_reviews.each do |review|
          .media
            %a.pull-left{:href => book_path(review.book)}
              = image_tag(review.book.cover.url(:icon))
            .media-body
              %h5.media-heading
                = review.book.title
                %span.badge= review.rating
              = review.details.to(83)
    .well
      %h2 Lists
      %br
      %br
      %br
      %br
      %br
      %br
      %br
      %br

= javascript_include_tag "jquerypp.custom.js"
= javascript_include_tag "jquery.bookblock.js"
%script{:type => "text/javascript"}
  :plain 

    var Page = (function() {
      var $grid = $( '#bb-custom-grid' );
      return {
        init : function() {
          $grid.find( 'div.bb-bookblock' ).each( function( i ) {

            var $bookBlock = $( this ),
            $nav = $bookBlock.next().children( 'span' ),
            bb = $bookBlock.bookblock( {
              speed : 600,
              shadows : false
            } );

            // add navigation events
            $nav.each( function( i ) {
              $( this ).on( 'click touchstart', function( event ) {
                var $dot = $( this );
                $nav.removeClass( 'bb-current' );
                $dot.addClass( 'bb-current' );
                $bookBlock.bookblock( 'jump', i + 1 );
                return false;
              } );
            } );

            // add swipe events
            $bookBlock.children().on( {
              'swipeleft' : function( event ) {
                $bookBlock.bookblock( 'next' );
                return false;
              },
              'swiperight' : function( event ) {
                $bookBlock.bookblock( 'prev' );
                return false;
              }

            } );

          } );
        }
      };

    })();

%script{:type => "text/javascript"}
  :plain 

      Page.init();